### ISSUE TITLE
New is_shop_expressions added to StreetComplete

### ISSUE THREAD

**Issue by dbdean** [mnalis/StreetComplete-taginfo-categorize#10]
I won't have time to do the PR until this weekend, so this issue will serve as a reminder for me and/or if @mnalis wants to do it themselves prior to then.

https://github.com/streetcomplete/StreetComplete/pull/3982 added office={telecommunication, it, lawyer, accountant} into the shop expression and the tags to remove stuff needs to be updated.

**Comment by dbdean** [comment]
Thanks, @mnalis!

**Comment by mnalis** [comment]
thank _you_, @dbdean
