### ISSUE TITLE
isShopExpressionFragment updated

### ISSUE THREAD

**Issue by westnordost** [mnalis/StreetComplete-taginfo-categorize#11]
I updated isShopExpressionFragment, it now includes anything that could be in a (non-purpose-built) building, i.e. also any office, craft etc.

Right very now, it is still on the [shops-overlay](https://github.com/streetcomplete/StreetComplete/tree/shops-overlay) branch but I will merge it to master today.

Not sure what I need to do here, I'd rather leave this up to you.

**Comment by mnalis** [comment]
(note to self - look into this commit: https://github.com/streetcomplete/StreetComplete/commit/4f462a1d15c1eb9660e879901c403a4af4ff7be8)

**Comment by westnordost** [comment]
ping

**Comment by mnalis** [comment]
Working on that. 

The new update is done in https://github.com/mnalis/StreetComplete-taginfo-categorize/commit/e0e514f3974f80de731201c4a337327890e70e9b, but as the change was quite extensive, it brought about `290` new keys that need classification, so it will likely take few more days before I get them all sorted out.
