### ISSUE TITLE
extension of shops/places - currently only processing of detected keys.txt (+ PR to SC) are needed

### ISSUE THREAD

**Issue by matkoniecz** [mnalis/StreetComplete-taginfo-categorize#12]
See

https://github.com/streetcomplete/StreetComplete/pull/5373#issuecomment-1933019930

https://github.com/streetcomplete/StreetComplete/issues/5152#issuecomment-1933021434

list of relevant object got extended.

Do you want help with reviewing/classifying tags?

**Comment by mnalis** [comment]
> Do you want help with reviewing/classifying tags?

Thanks for offer @matkoniecz; it would be much appreciated if you have some spare time!

There are already a few dozen `TODO` entries in `keys.txt` to move to correct category too, in addition to the comments you linked (which I need to take some time to properly understood, but won't have before next week unfortunately)

**Comment by mnalis** [comment]
`club` key encoding issue from https://github.com/mnalis/StreetComplete-taginfo-categorize/pull/21 is fixed, and has added new TODOs to `keys.txt`

**Comment by matkoniecz** [comment]
Oh and if you finished processing for today - feel free to ping me, maybe I will look into it again this evening

**Comment by mnalis** [comment]
thanks @matkoniecz feel free to continue, I'm done for today

**Comment by matkoniecz** [comment]
And I am also done for today and probably tomorrow...

Oh and thanks for taming that club group!

**Comment by mnalis** [comment]
done in https://github.com/streetcomplete/StreetComplete/pull/5501

thanks again for all the help!

**Comment by matkoniecz** [comment]
And also thanks for help and you work on this project!
