### ISSUE TITLE
Unclear error - make: *** [Makefile:60: stats] Error 1

### ISSUE THREAD

**Issue by matkoniecz** [mnalis/StreetComplete-taginfo-categorize#13]
I tried running `make update` but got `make: *** [Makefile:60: stats] Error 1` without other hints

**Comment by mnalis** [comment]
Doesn't it output something like `TODO : 45` in a line immediately above that @matkoniecz ?

The intention is to convey that one has to fix (categorize) `45` more `TODO` entries before it can proceed / finish.

Would something like `TODO: 45 (must be categorized before continuing)` be better? Or some other text / docs?

**Comment by matkoniecz** [comment]
Would adding "at the end in keys.txt file" would make sense and be accurate?

**Comment by matkoniecz** [comment]
Thanks, now I am no longer confused at all
