### ISSUE TITLE
repo description and readme

### ISSUE THREAD

**Issue by matkoniecz** [mnalis/StreetComplete-taginfo-categorize#18]
repo description

>  update list of tags combined with shop=*, craft=* etc. to populate and categorise tags related to inverse of KEYS_THAT_SHOULD_NOT_BE_REMOVED_WHEN_SHOP_IS_REPLACED in StreetComplete 

can be

>  update list of tags combined with shop=*, craft=* etc. to populate and categorise tags related to KEYS_THAT_SHOULD_BE_REMOVED_WHEN_PLACE_IS_REPLACED listing in StreetComplete 

I cannot open PR as it is defined not in repo but in github specific proprietary interface and I have no administration rights to change repository settings

**Comment by mnalis** [comment]
Thanks, updated repo description. 

(I also need to update the code / docs itself too)

**Comment by mnalis** [comment]
@matkoniecz I'm looking at https://github.com/streetcomplete/StreetComplete/commit/cb1ef5ada6873ffd9e85afefedf483e98c3932f0 and trying to understand what happened with `isShopExpressionFragment()` and how is it replaced, but those seem quite a big changes... How that works now?

I need that to update related `isShopExpressionFragment()` parts of https://github.com/mnalis/StreetComplete-taginfo-categorize/blob/master/README.md documentation. Could you help with explanation, or maybe even a PR for `README.md` section `when isShopExpressionFragment() changes`?

**Comment by matkoniecz** [comment]
Things overlay has appeared (or will appear in F-droid and will appear in Google Play once Google will allow to release it).

Shops overlay become Places overlay with more widely defined coverage.

IS_PLACE_EXPRESSION replaces older shop listing.
