### ISSUE TITLE
generate FETCH_TAGS automatically based on StreetComplete code

### ISSUE THREAD

**Issue by mnalis** [mnalis/StreetComplete-taginfo-categorize#19]
As noted in https://github.com/mnalis/StreetComplete-taginfo-categorize/pull/17 it would be nice if StreetComplete-taginfo-categorize could generate `FETCH_TAGS`  automatically based on StreetComplete code

**Comment by mnalis** [comment]
@matkoniecz do you mean generating `FETCH_TAGS` from `private val IS_PLACE_EXPRESSION` in https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt ?

I'm that `IS_PLACE_EXPRESSION` replacing old `isShopExpressionFragment()` as asked in https://github.com/mnalis/StreetComplete-taginfo-categorize/issues/18#issuecomment-1955099104 ?

**Comment by matkoniecz** [comment]
> IS_PLACE_EXPRESSION

yes

> I'm that IS_PLACE_EXPRESSION replacing old isShopExpressionFragment() as asked in https://github.com/mnalis/StreetComplete-taginfo-categorize/issues/18#issuecomment-1955099104 ?

yes

**Comment by matkoniecz** [comment]
> As noted in https://github.com/mnalis/StreetComplete-taginfo-categorize/pull/17 it would be nice if StreetComplete-taginfo-categorize could generate FETCH_TAGS automatically based on StreetComplete code

I guess that it has few pieces/levels of automation

1) run it automatically - either when script is run or in github CI (any preference here?)

2) getting/parsing data and outputting it to a file

3) changing perl script to load FETCH_TAGS list from file

I though about making it a Kotlin script that would get https://raw.githubusercontent.com/streetcomplete/StreetComplete/master/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt append some extra Kotlin code to it and then run such Kotlin script.

Main negative is that repo would get an extra language and runtime environment necessary to run it.
Positive thing is that Kotlin script gets parsing of Kotlin for free.

**Comment by matkoniecz** [comment]
So questions:

- is it ok to have code for that written in Kotlin?
- should it be primarily running in github CI? Or locally? Or both?

(if Perl is needed then I give up on that, I never wrote things in Perl and I am not really wanting to start - if Kotlin is OK then I would at least try. I am unsure about Githu CI runner but can try, I would be fine with running it locally on Linux - but I would not be able to test it on Windows)

**Comment by mnalis** [comment]
> Main negative is that repo would get an extra language and runtime environment necessary to run it.

Yeah, I'm really not liking that requirement...

>  Positive thing is that Kotlin script gets parsing of Kotlin for free.

True, but another issue is that while Kotlin would parse that code ideally (e.g. `or tourism = information and information ~ office|visitor_centre`) the taginfo (on which the scripts here depend on) **can't**. So, the Makefile already has manually simplified rules for the likes of those rules.

---

So my idea is to parse [that generically-formated first (biggest) part](https://github.com/streetcomplete/StreetComplete/blob/v57.0-beta1/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt#L35-L191) in perl (probably with quick&dirty regexes) and generate `FETCH_TAGS` pairs out of them, and for the remaining part (hopefully much less likely to change) require human intervention to convert them manually to either imperfect `FETCH_TAGS` or `FETCH_KEYS`. 

Perhaps detect the change and raise alert if the text of that [complex second part](https://github.com/streetcomplete/StreetComplete/blob/d0db3f4968afe113079752aa6e194f1853a46e9c/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt#L193-L202) change there from last-validated commit? But that sounds like overkill probably... How often do we expect that it would change?

**Comment by matkoniecz** [comment]
> True, but another issue is that while Kotlin would parse that code ideally (e.g. or tourism = information and information ~ office|visitor_centre) the taginfo (on which the scripts here depend on) can't.

my idea was to do simplification automatically

> So my idea is to parse [that generically-formated first (biggest) part](https://github.com/streetcomplete/StreetComplete/blob/v57.0-beta1/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt#L35-L191) in perl (probably with quick&dirty regexes)

Are you planning and being able to implement it soon? If not then I can have one-off solution (likely in Kotlin, maybe manual) and will update current list to get support for upcoming release.

**Comment by matkoniecz** [comment]
Hmm, maybe for start just checking whether file was updated (and getting hash of contents or of last git commit that affected it) would be nice start? With manual applying of changes?

**Comment by mnalis** [comment]
> Hmm, maybe for start just checking whether file was updated (and getting hash of contents or of last git commit that affected it) would be nice start? With manual applying of changes?

I've added that check now; please see if updated [README.md](https://github.com/mnalis/StreetComplete-taginfo-categorize/blob/master/README.md#when-is_place_expression-in-placekt-changes) instructions make sense to you

**Comment by matkoniecz** [comment]
Seems to make sense

Not sure whether this ticket should remain open

**Comment by mnalis** [comment]
well then, let's close it for now. I guess `Place.kt` won't be changing so often so that keeping those in sync would be significant work to warrant semi-automation anyway...

Especially as now we have an old git commit, so when `Place.kt` does change, we can easily do:

```
git diff 8e4042f95.. -- app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt
```

(where `8e4042f95` is from `STREETCOMPLETE_LAST_GIT` from `Makefile`)

and see what keys/tags were being added/removed in StreetComplete since that commit.
