### ISSUE TITLE
fhrs

### ISSUE THREAD

**Issue by Cj-Malone** [mnalis/StreetComplete-taginfo-categorize#2]
When a POI with `fhrs:id` closes it should be removed, it's definitely about the shop/restaurant and not the building or address.

All other `fhrs:*` ( `fhrs:local_authority_id` `fhrs:authority` `fhrs:rating` `fhrs:rating_date` `fhrs:hygiene` `fhrs:structural` `fhrs:confidence_management` ) are basically deprecated and duplicate unnecessary data. They should also be removed when a POI closes, most of the time they should be removed even when while it's open.

**Comment by mnalis** [comment]
thanks! added
