### ISSUE TITLE
Discard all check_dates?

### ISSUE THREAD

**Issue by kmpoppe** [mnalis/StreetComplete-taginfo-categorize#26]
https://github.com/mnalis/StreetComplete-taginfo-categorize/blob/d587c81f7f656ccd27d1c0d99d785dadd15a92c2/keys.txt#L86

This just throws away `check_date`, but for quite some time, SC also created `check_date:*=*`, so should that line read `check_date(:.*)?`?

**Comment by mnalis** [comment]
Well, it depends on what was checked, e.g. on removal of shop:
- `check_date:opening_hours` and `check_date:contact:facebook` should be removed
- `check_date:addr` and `check_date:building:levels` should remain

If you look, `keys.txt` _does_ addresses few  of them (those that occur as combination more than `$min_percent = 0.01%` times in  taginfo in combination with shop).


Ideally, _all_ the `check_date:*` keys that are mentioned in `KEYS TO REMOVE` should be removed, and all `check_date:*` keys that are mentioned in `KEYS TO KEEP` should be kept. But if we were to go that way, it should probably be done programmatically in SC (and not via copy/paste duplication here)

---

Note that this repo could potentially be used by other apps than StreetComplete (to avoid reinventing the wheel), so it only looks at Taginfo, not at StreetComplete code specifics -- and SC seems to have separate `check_date:*` handling (although I've not investigated what `removeCheckDates()` actually does, i.e.:

https://github.com/streetcomplete/StreetComplete/blob/v59.0/app/src/main/java/de/westnordost/streetcomplete/osm/Place.kt#L248-L255
