### ISSUE TITLE
maybe store file as UTF-8?

### ISSUE THREAD

**Issue by matkoniecz** [mnalis/StreetComplete-taginfo-categorize#28]
per github: "We’ve detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8."

is github misdetecting it? Or is it actually in weird encoding and can be converted to standard UTF-8?

**Comment by mnalis** [comment]
(ref. breakage in closed PR https://github.com/mnalis/StreetComplete-taginfo-categorize/pull/25)

It also seems the issue was encoutered before too: https://github.com/mnalis/StreetComplete-taginfo-categorize/commit/d5c5346f1fda0cabbcc9dc55930c215173d70869

**Comment by mnalis** [comment]
Well not actually fixed in code, but the problem is gone, as the problematic key in no longer in database, see https://community.openstreetmap.org/t/faroe-islands-address-metadata-cleanup-proposed-mass-edit/109790/5

If it happens with another UTF8 tag, we can debug it then...
